import type { Question, ScaleOption } from '@/types'

// Standard scale labels — used for all scale-type questions
export const SCALE_OPTIONS: ScaleOption[] = [
  { value: 0, label: 'Нет совсем', description: 'Не существует, не применяется' },
  { value: 1, label: 'Есть кое-что, но без системы', description: 'Есть отдельные попытки, единичные случаи' },
  { value: 2, label: 'Есть, но большие пробелы', description: 'Реализовано частично, видны значимые пробелы' },
  { value: 3, label: 'В основном работает', description: 'Большая часть работает, единичные пробелы' },
  { value: 4, label: 'Работает системно', description: 'Внедрено и поддерживается системно' },
  { value: 5, label: 'Отлично — задокументировано и развивается', description: 'Эталонный уровень: задокументировано, регулярно обновляется' },
]

// ─── K — Knowledge Architecture ──────────────────────────────────────────────

const K_QUESTIONS: Question[] = [
  {
    id: 'K1',
    module: 'K',
    criterionId: 'K_process_docs',
    criterionLabel: 'Документация процессов',
    text: 'Записаны ли ваши ключевые рабочие процессы? Есть ли инструкции, регламенты, описания — как что делается?',
    tooltip: '0 — ничего не записано, всё в головах. 5 — все процессы описаны, актуальны, обновляются.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'Процессы не описаны',
      description: 'Без записанных процессов AI-внедрение невозможно контролировать: непонятно, что автоматизировать и как.',
    },
  },
  {
    id: 'K2',
    module: 'K',
    criterionId: 'K_roles',
    criterionLabel: 'Роли и ответственности',
    text: 'Каждый в команде знает, за что он отвечает? Нет ли ситуаций «я думал, это делает он»?',
    tooltip: '0 — роли размыты, постоянные конфликты ответственности. 5 — у каждого чёткая зона без пересечений.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'Размытые роли',
      description: 'При внедрении AI без чётких ролей теряется контроль: непонятно, кто отвечает за результат AI.',
    },
  },
  {
    id: 'K3',
    module: 'K',
    criterionId: 'K_data_arch',
    criterionLabel: 'Единый источник данных',
    text: 'Есть ли одно главное место, где хранятся актуальные данные компании? Или информация разбросана по чатам, таблицам и головам людей?',
    tooltip: '0 — данные везде и нигде, постоянные противоречия. 5 — есть одна «главная» система, все берут данные оттуда.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 2,
      level: 'P0',
      label: 'Хаос данных',
      description: 'AI работает на данных. Если данные разбросаны и противоречат друг другу — AI будет принимать неверные решения.',
    },
  },
  {
    id: 'K4',
    module: 'K',
    criterionId: 'K_dependencies',
    criterionLabel: 'Карта зависимостей',
    text: 'Если один инструмент или сотрудник выбывает — понятно ли, что ещё перестанет работать?',
    tooltip: '0 — связи непонятны, каждый сбой — сюрприз. 5 — есть карта зависимостей, последствия сбоев известны.',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'K5',
    module: 'K',
    criterionId: 'K_knowledge_transfer',
    criterionLabel: 'Передача знаний',
    text: 'Если ключевой сотрудник уйдёт завтра — насколько быстро его заменят? Есть ли онбординг и база знаний?',
    tooltip: '0 — всё держится в голове одного человека. 5 — есть онбординг, база знаний, замена происходит без потрясений.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P1',
      label: 'Всё держится на одном человеке',
      description: 'Зависимость от одного носителя знания — критический риск при масштабировании и при AI-внедрении.',
    },
  },
  {
    id: 'K6',
    module: 'K',
    criterionId: 'K_ops_map',
    criterionLabel: 'Операционная карта',
    text: 'Есть ли таблица или схема: кто что делает, в каком инструменте и на каком этапе?',
    tooltip: '0 — нет такой схемы. 5 — есть актуальная операционная карта, все ею пользуются.',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'K7',
    module: 'K',
    criterionId: 'K_wiki',
    criterionLabel: 'Единое хранилище',
    text: 'Есть ли одно место, куда команда складывает документы и инструкции — например, Notion, Google Drive или внутренняя вики?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, есть и все активно используют' },
      { value: 2, label: 'Есть, но пользуются непоследовательно' },
      { value: 0, label: 'Нет, документы везде и нигде' },
    ],
    scoring: false,
    riskIndicator: {
      threshold: 0,
      level: 'P1',
      label: 'Нет общей базы знаний',
      description: 'Без единого хранилища документация разрознена, теряется при смене людей.',
    },
  },
  {
    id: 'K8',
    module: 'K',
    criterionId: 'K_review_freq',
    criterionLabel: 'Ревью процессов',
    text: 'Как часто вы садитесь и пересматриваете: а актуальны ли наши процессы?',
    type: 'choice',
    options: [
      { value: 0, label: 'Никогда — процессы не менялись годами' },
      { value: 1, label: 'Один раз за всё время' },
      { value: 3, label: 'Иногда — раз в год или реже' },
      { value: 4, label: 'Регулярно — раз в квартал и чаще' },
    ],
    scoring: false,
  },
  {
    id: 'K9',
    module: 'K',
    criterionId: 'K_bottleneck',
    criterionLabel: 'Узкие места',
    text: 'Знаете ли вы, где в вашем бизнесе чаще всего «застревают» задачи или теряется информация?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, знаем и работаем над устранением' },
      { value: 2, label: 'Частично понимаем' },
      { value: 0, label: 'Нет, не отслеживали' },
    ],
    scoring: false,
  },
]

// ─── A — AI System Design ─────────────────────────────────────────────────────

const A_QUESTIONS: Question[] = [
  {
    id: 'A1',
    module: 'A',
    criterionId: 'A_use_cases',
    criterionLabel: 'Стратегия применения AI',
    text: 'Есть ли у вас список задач, где вы применяете или планируете применять AI? Или инструменты появляются стихийно — увидели, попробовали?',
    tooltip: 'Если AI пока не используете — выберите 0. Это нормально и тоже является результатом оценки.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'AI без стратегии',
      description: 'Стихийное внедрение AI создаёт хаос и блокирует дальнейший рост — каждый следующий инструмент усиливает беспорядок.',
    },
  },
  {
    id: 'A2',
    module: 'A',
    criterionId: 'A_layer_integrity',
    criterionLabel: 'AI в рабочих процессах',
    text: 'Ваши AI-инструменты встроены в рабочий процесс — или каждый пользуется ими отдельно, сам по себе?',
    tooltip: '0 — AI-инструменты используются изолированно. 5 — AI встроен в процессы, данные передаются автоматически. Если AI не используете — выберите 0.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 2,
      level: 'P0',
      label: 'AI не встроен в процессы',
      description: 'AI как отдельный инструмент не меняет систему — он добавляет ещё один элемент хаоса.',
    },
  },
  {
    id: 'A3',
    module: 'A',
    criterionId: 'A_integrations',
    criterionLabel: 'Связность инструментов',
    text: 'Ваши AI-инструменты и другие программы обмениваются данными автоматически — или сотрудники переносят данные вручную?',
    tooltip: '0 — всё вручную, данные копируются между системами. 5 — инструменты связаны, данные передаются автоматически. Если AI не используете — выберите 0.',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'A4',
    module: 'A',
    criterionId: 'A_control',
    criterionLabel: 'Контроль AI-процессов',
    text: 'Вы узнаёте об ошибке в AI-инструменте сразу — или случайно, уже после того как что-то пошло не так?',
    tooltip: '0 — узнаём случайно. 5 — есть уведомления о сбоях, кто-то следит за работой AI. Если AI не используете — выберите 0.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'AI без контроля',
      description: 'AI-процессы без мониторинга накапливают ошибки незаметно — последствия обнаруживаются слишком поздно.',
    },
  },
  {
    id: 'A5',
    module: 'A',
    criterionId: 'A_vendor_risk',
    criterionLabel: 'Зависимость от AI-сервисов',
    text: 'Что будет, если один из ваших AI-сервисов закроется или станет в 5 раз дороже? Есть ли запасной вариант?',
    tooltip: '0 — нет запасного варианта, бизнес встанет. 5 — есть план Б для каждого критичного сервиса. Если AI не используете — выберите 0.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P1',
      label: 'Нет плана Б для AI-сервисов',
      description: 'Отказ одного AI-сервиса без запасного варианта может остановить ключевые бизнес-процессы.',
    },
  },
  {
    id: 'A6',
    module: 'A',
    criterionId: 'A_governance',
    criterionLabel: 'Правила работы с AI',
    text: 'Есть ли у вас правила: кто может использовать AI-инструменты, какие данные туда загружать, кто отвечает за результат?',
    tooltip: '0 — правил нет, каждый делает как хочет. 5 — есть политика, доступы ограничены, ответственность распределена. Если AI не используете — выберите 0.',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'A7',
    module: 'A',
    criterionId: 'A_tool_count',
    criterionLabel: 'Сколько AI-инструментов',
    text: 'Сколько AI-инструментов и сервисов сейчас используется в вашем бизнесе?',
    type: 'choice',
    options: [
      { value: 2, label: 'Не используем AI — пока не начали' },
      { value: 5, label: '1–3 инструмента' },
      { value: 4, label: '4–10 инструментов' },
      { value: 2, label: 'Более 10 — много разных, без системы' },
    ],
    scoring: false,
  },
  {
    id: 'A8',
    module: 'A',
    criterionId: 'A_owner',
    criterionLabel: 'Кто отвечает за AI',
    text: 'Есть ли в команде кто-то, кто отвечает за то, как устроен AI в бизнесе в целом — не просто пользуется, а думает о системе?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, есть выделенный человек или роль' },
      { value: 2, label: 'Кто-то занимается этим в числе прочих задач' },
      { value: 1, label: 'Пока не используем AI' },
      { value: 0, label: 'Нет — каждый действует сам по себе' },
    ],
    scoring: false,
    riskIndicator: {
      threshold: 0,
      level: 'P1',
      label: 'Нет ответственного за AI',
      description: 'Без владельца AI-стратегии каждый внедряет что хочет — система не строится, она случайно накапливается.',
    },
  },
  {
    id: 'A9',
    module: 'A',
    criterionId: 'A_data_flow',
    criterionLabel: 'Движение данных',
    text: 'Записано ли где-нибудь, как данные перемещаются между вашими AI-инструментами и другими программами?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, схемы есть и актуальны' },
      { value: 2, label: 'Частично — кое-что зафиксировано' },
      { value: 1, label: 'Не используем AI' },
      { value: 0, label: 'Нет' },
    ],
    scoring: false,
  },
]

// ─── Q — Quality & Risk Control ───────────────────────────────────────────────

const Q_QUESTIONS: Question[] = [
  {
    id: 'Q1',
    module: 'Q',
    criterionId: 'Q_error_handling',
    criterionLabel: 'Обнаружение ошибок',
    text: 'Когда AI-инструмент или автоматизация работает неправильно — как вы об этом узнаёте?',
    tooltip: '0 — узнаём случайно или не узнаём вовсе. 5 — сразу приходит уведомление, есть план действий. Если AI не используете — ставьте 0.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'Ошибки AI не видны',
      description: 'Если ошибки в AI-процессах не обнаруживаются сразу — они накапливаются и приводят к системным сбоям.',
    },
  },
  {
    id: 'Q2',
    module: 'Q',
    criterionId: 'Q_testing',
    criterionLabel: 'Проверка AI-процессов',
    text: 'Проверяете ли вы, что AI и автоматизация работают правильно — особенно когда что-то меняется?',
    tooltip: '0 — не проверяем никогда. 5 — регулярные проверки, тесты после каждого изменения. Если AI не используете — ставьте 0.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'AI не проверяется',
      description: 'Без проверок любое обновление AI-инструмента может незаметно сломать работающие процессы.',
    },
  },
  {
    id: 'Q3',
    module: 'Q',
    criterionId: 'Q_security',
    criterionLabel: 'Безопасность данных в AI',
    text: 'Контролируете ли вы, какие данные компании и клиентов попадают в AI-инструменты? Есть ли правила, что можно передавать, а что нельзя?',
    tooltip: '0 — нет контроля, данные передаются без ограничений. 5 — чёткие правила, контроль доступов, проверки.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 2,
      level: 'P0',
      label: 'Данные утекают через AI',
      description: 'Без контроля данных конфиденциальная информация клиентов и компании передаётся в сторонние AI-сервисы бесконтрольно.',
    },
  },
  {
    id: 'Q4',
    module: 'Q',
    criterionId: 'Q_regression',
    criterionLabel: 'Проверка после изменений',
    text: 'Когда обновляется AI-инструмент или меняются его настройки — проверяете ли, что всё остальное по-прежнему работает как надо?',
    tooltip: '0 — не проверяем, узнаём о проблемах случайно. 5 — есть чеклист проверки после каждого изменения. Если AI нет — ставьте 0.',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'Q5',
    module: 'Q',
    criterionId: 'Q_failure_points',
    criterionLabel: 'Критичные точки отказа',
    text: 'Знаете ли вы, что в вашем бизнесе «упадёт» первым при сбое? Есть ли запасные варианты для самых важных процессов?',
    tooltip: '0 — не знаем, каждый сбой — сюрприз. 5 — все критичные точки известны, для каждой есть план Б.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 2,
      level: 'P0',
      label: 'Нет плана при сбоях',
      description: 'Неизвестные точки отказа — это «мины» в операционной системе бизнеса.',
    },
  },
  {
    id: 'Q6',
    module: 'Q',
    criterionId: 'Q_incidents',
    criterionLabel: 'Реакция на сбои',
    text: 'Когда что-то сломалось — есть ли чёткий сценарий: кто что делает, за какое время должен исправить?',
    tooltip: '0 — каждый раз хаос. 5 — есть регламент, роли расписаны, сроки фиксированы.',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'Q7',
    module: 'Q',
    criterionId: 'Q_recent_incident',
    criterionLabel: 'Сбои за последние полгода',
    text: 'Был ли за последние 6 месяцев сбой, который остановил или серьёзно замедлил работу бизнеса?',
    type: 'choice',
    options: [
      { value: 0, label: 'Да, критический — бизнес останавливался' },
      { value: 1, label: 'Да, несколько серьёзных инцидентов' },
      { value: 3, label: 'Да, но всё было незначительным' },
      { value: 5, label: 'Нет, всё работало стабильно' },
    ],
    scoring: false,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'Недавние серьёзные сбои',
      description: 'История сбоев указывает на системные проблемы, которые нужно устранить до расширения AI.',
    },
  },
  {
    id: 'Q8',
    module: 'Q',
    criterionId: 'Q_dr_plan',
    criterionLabel: 'План на случай сбоя',
    text: 'Если завтра упадёт главный инструмент или сервер — есть ли план, как восстановить работу и за сколько часов?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, план есть и мы его проверяли' },
      { value: 2, label: 'Что-то есть, но давно не обновляли' },
      { value: 0, label: 'Нет, будем разбираться по ходу' },
    ],
    scoring: false,
    riskIndicator: {
      threshold: 0,
      level: 'P1',
      label: 'Нет плана восстановления',
      description: 'Без плана восстановления при серьёзном сбое команда будет тратить часы на решение, которое могло занять минуты.',
    },
  },
  {
    id: 'Q9',
    module: 'Q',
    criterionId: 'Q_logging',
    criterionLabel: 'История действий AI',
    text: 'Хранится ли история того, что делали ваши AI-инструменты? Можно ли разобраться задним числом, где пошло не так?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, всё фиксируется централизованно' },
      { value: 2, label: 'Частично — кое-что сохраняется' },
      { value: 1, label: 'Не используем AI' },
      { value: 0, label: 'Нет' },
    ],
    scoring: false,
  },
]

// ─── S — Scalability Framework ────────────────────────────────────────────────

const S_QUESTIONS: Question[] = [
  {
    id: 'S1',
    module: 'S',
    criterionId: 'S_growth_plan',
    criterionLabel: 'План роста',
    text: 'Есть ли зафиксированный план роста системы на 12+ месяцев?',
    tooltip: 'Известны ли точки масштабирования? Что будет делаться при росте x2, x5, x10?',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P1',
      label: 'Нет стратегии роста',
      description: 'Без плана роста AI-системы рост бизнеса будет требовать переписывания архитектуры с нуля.',
    },
  },
  {
    id: 'S2',
    module: 'S',
    criterionId: 'S_modularity',
    criterionLabel: 'Модульность',
    text: 'Насколько модульна архитектура системы (можно менять части, не трогая целое)?',
    tooltip: '0 — всё переплетено, любое изменение ломает другое, 5 — чёткая модульная архитектура, слабые связи между компонентами.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'Монолитная хрупкая система',
      description: 'Немодульная система блокирует масштабирование: любое изменение ломает существующее.',
    },
  },
  {
    id: 'S3',
    module: 'S',
    criterionId: 'S_load',
    criterionLabel: 'Устойчивость к нагрузке',
    text: 'Готова ли инфраструктура к росту объёмов в 3–5 раз без переписывания?',
    tooltip: 'Тестировалась ли система под нагрузкой? Известны ли узкие места при масштабировании?',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'S4',
    module: 'S',
    criterionId: 'S_resources',
    criterionLabel: 'Ресурсное планирование',
    text: 'Насколько спланированы ресурсы для поддержки и развития системы при росте?',
    tooltip: 'Люди, бюджет, инструменты — что потребуется при росте? Есть ли план найма/развития команды?',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'S5',
    module: 'S',
    criterionId: 'S_metrics',
    criterionLabel: 'Метрики устойчивости',
    text: 'Есть ли метрики устойчивости системы (uptime, latency, error rate, throughput)?',
    tooltip: '0 — никаких метрик нет, 5 — метрики собираются, есть dashboards и пороговые алерты.',
    type: 'scale',
    scoring: true,
    riskIndicator: {
      threshold: 1,
      level: 'P1',
      label: 'Нет метрик устойчивости',
      description: 'Без метрик невозможно управлять ростом: деградация системы будет незаметна до критической точки.',
    },
  },
  {
    id: 'S6',
    module: 'S',
    criterionId: 'S_automation',
    criterionLabel: 'Автоматизация масштабирования',
    text: 'Насколько автоматизированы процессы при увеличении объёмов?',
    tooltip: '0 — всё ручное, 5 — масштабирование автоматическое (автоматическое добавление ресурсов, роутинг, балансировка).',
    type: 'scale',
    scoring: true,
  },
  {
    id: 'S7',
    module: 'S',
    criterionId: 'S_break_freq',
    criterionLabel: 'Частота сбоев при росте',
    text: 'Как часто система ломается или деградирует при росте объёмов или нагрузки?',
    type: 'choice',
    options: [
      { value: 0, label: 'Постоянно — рост = сбои' },
      { value: 1, label: 'Часто — раз в несколько недель' },
      { value: 3, label: 'Редко — единичные случаи' },
      { value: 5, label: 'Никогда или почти никогда' },
    ],
    scoring: false,
    riskIndicator: {
      threshold: 1,
      level: 'P0',
      label: 'Система ломается при росте',
      description: 'Регулярные сбои при нагрузке — системный архитектурный дефект, не операционная проблема.',
    },
  },
  {
    id: 'S8',
    module: 'S',
    criterionId: 'S_scale_docs',
    criterionLabel: 'Документация масштабирования',
    text: 'Задокументированы ли точки масштабирования (где, как и когда расширять)?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, подробно' },
      { value: 2, label: 'Частично' },
      { value: 0, label: 'Нет' },
    ],
    scoring: false,
  },
  {
    id: 'S9',
    module: 'S',
    criterionId: 'S_delegation',
    criterionLabel: 'Делегирование без потери контроля',
    text: 'Возможно ли делегировать управление частями системы без потери контроля и качества?',
    type: 'boolean',
    options: [
      { value: 5, label: 'Да, есть стандарты и инструкции' },
      { value: 2, label: 'Частично' },
      { value: 0, label: 'Нет, слишком много зависит от меня' },
    ],
    scoring: false,
  },
]

// ─── Export ───────────────────────────────────────────────────────────────────

export const ALL_QUESTIONS: Question[] = [
  ...K_QUESTIONS,
  ...A_QUESTIONS,
  ...Q_QUESTIONS,
  ...S_QUESTIONS,
]

export const QUESTIONS_BY_MODULE: Record<string, Question[]> = {
  K: K_QUESTIONS,
  A: A_QUESTIONS,
  Q: Q_QUESTIONS,
  S: S_QUESTIONS,
}

export const MODULE_META = {
  K: { label: 'Knowledge Architecture', shortLabel: 'Knowledge', color: '#1F5F5B' },
  A: { label: 'AI System Design', shortLabel: 'AI Design', color: '#1F5F5B' },
  Q: { label: 'Quality & Risk Control', shortLabel: 'Quality', color: '#1F5F5B' },
  S: { label: 'Scalability Framework', shortLabel: 'Scalability', color: '#1F5F5B' },
} as const
